# Generated by Django 6.0.7 on 2026-08-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membros',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
